version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - "REDIS_PASSWORD="
      - "REDIS_KEY_PREFIX=motorway:"
      - DATABASE_PATH=/app/data/database.sqlite
      - CACHE_TTL_PROVIDER_HEALTH=900
      - CACHE_TTL_LEADER_LOCK=30
      - CACHE_TTL_PROVIDER_STATS=300
      - "CACHE_KEY_PROVIDER_HEALTH=provider:health:"
      - "CACHE_KEY_LEADER_LOCK=leader:lock"
      - "CACHE_KEY_PROVIDER_STATS=provider:stats:"
    volumes:
      - ./data:/app/data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 